//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.4.4
//     from Assets/MainKeys.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @MainKeys : IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @MainKeys()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""MainKeys"",
    ""maps"": [
        {
            ""name"": ""Playing"",
            ""id"": ""ce623308-30e1-4f39-add3-81a5258cd791"",
            ""actions"": [
                {
                    ""name"": ""Line1"",
                    ""type"": ""Button"",
                    ""id"": ""8d78eb3f-a8c1-4655-b26f-72adb32dd7f8"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Line2"",
                    ""type"": ""Button"",
                    ""id"": ""a1863012-3423-49eb-9d17-dbc92cf4f46b"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Line3"",
                    ""type"": ""Button"",
                    ""id"": ""ae9049e6-712b-47b9-9b3f-88a721816d58"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Line4"",
                    ""type"": ""Button"",
                    ""id"": ""1385d743-d2cb-4daa-bdcc-7cb9bcefb9c7"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Line5"",
                    ""type"": ""Button"",
                    ""id"": ""e2bfe418-cda3-40b1-abd2-31b936f1dbaa"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Line6"",
                    ""type"": ""Button"",
                    ""id"": ""c41a6345-81af-4074-8990-cd11899cb0dd"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Line8"",
                    ""type"": ""Button"",
                    ""id"": ""ca694f25-b923-4089-81de-bd2c9a9e3f5a"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Line9"",
                    ""type"": ""Button"",
                    ""id"": ""146e6041-877a-4f7f-a3f7-7f831da807c9"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""1ccd7eb3-8bd2-4246-8838-ebaec2add54d"",
                    ""path"": ""<Keyboard>/s"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Line1"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""6ec6c389-86d3-424f-b988-88ad539c41e8"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Line2"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""c706a43a-8c33-4ddd-bdde-a7af2f321e6d"",
                    ""path"": ""<Keyboard>/f"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Line3"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""2599cc5f-e4e5-49bd-9453-2cbaebaf50e3"",
                    ""path"": ""<Keyboard>/space"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Line4"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""46289f19-b53f-46de-b55a-eb484e2f30cc"",
                    ""path"": ""<Keyboard>/j"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Line5"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""c31b628b-72de-42fa-8c56-55d3506951f6"",
                    ""path"": ""<Keyboard>/leftShift"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Line6"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""715063bc-3910-4ed1-9a31-74954d2b7389"",
                    ""path"": ""<Keyboard>/slash"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Line6"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""c6534b15-593b-404f-a1bf-9b5b1be12102"",
                    ""path"": ""<Keyboard>/k"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Line8"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""258b4c5a-1ab8-4ccf-bb08-d5d454666342"",
                    ""path"": ""<Keyboard>/l"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Line9"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // Playing
        m_Playing = asset.FindActionMap("Playing", throwIfNotFound: true);
        m_Playing_Line1 = m_Playing.FindAction("Line1", throwIfNotFound: true);
        m_Playing_Line2 = m_Playing.FindAction("Line2", throwIfNotFound: true);
        m_Playing_Line3 = m_Playing.FindAction("Line3", throwIfNotFound: true);
        m_Playing_Line4 = m_Playing.FindAction("Line4", throwIfNotFound: true);
        m_Playing_Line5 = m_Playing.FindAction("Line5", throwIfNotFound: true);
        m_Playing_Line6 = m_Playing.FindAction("Line6", throwIfNotFound: true);
        m_Playing_Line8 = m_Playing.FindAction("Line8", throwIfNotFound: true);
        m_Playing_Line9 = m_Playing.FindAction("Line9", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }
    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }
    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // Playing
    private readonly InputActionMap m_Playing;
    private IPlayingActions m_PlayingActionsCallbackInterface;
    private readonly InputAction m_Playing_Line1;
    private readonly InputAction m_Playing_Line2;
    private readonly InputAction m_Playing_Line3;
    private readonly InputAction m_Playing_Line4;
    private readonly InputAction m_Playing_Line5;
    private readonly InputAction m_Playing_Line6;
    private readonly InputAction m_Playing_Line8;
    private readonly InputAction m_Playing_Line9;
    public struct PlayingActions
    {
        private @MainKeys m_Wrapper;
        public PlayingActions(@MainKeys wrapper) { m_Wrapper = wrapper; }
        public InputAction @Line1 => m_Wrapper.m_Playing_Line1;
        public InputAction @Line2 => m_Wrapper.m_Playing_Line2;
        public InputAction @Line3 => m_Wrapper.m_Playing_Line3;
        public InputAction @Line4 => m_Wrapper.m_Playing_Line4;
        public InputAction @Line5 => m_Wrapper.m_Playing_Line5;
        public InputAction @Line6 => m_Wrapper.m_Playing_Line6;
        public InputAction @Line8 => m_Wrapper.m_Playing_Line8;
        public InputAction @Line9 => m_Wrapper.m_Playing_Line9;
        public InputActionMap Get() { return m_Wrapper.m_Playing; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(PlayingActions set) { return set.Get(); }
        public void SetCallbacks(IPlayingActions instance)
        {
            if (m_Wrapper.m_PlayingActionsCallbackInterface != null)
            {
                @Line1.started -= m_Wrapper.m_PlayingActionsCallbackInterface.OnLine1;
                @Line1.performed -= m_Wrapper.m_PlayingActionsCallbackInterface.OnLine1;
                @Line1.canceled -= m_Wrapper.m_PlayingActionsCallbackInterface.OnLine1;
                @Line2.started -= m_Wrapper.m_PlayingActionsCallbackInterface.OnLine2;
                @Line2.performed -= m_Wrapper.m_PlayingActionsCallbackInterface.OnLine2;
                @Line2.canceled -= m_Wrapper.m_PlayingActionsCallbackInterface.OnLine2;
                @Line3.started -= m_Wrapper.m_PlayingActionsCallbackInterface.OnLine3;
                @Line3.performed -= m_Wrapper.m_PlayingActionsCallbackInterface.OnLine3;
                @Line3.canceled -= m_Wrapper.m_PlayingActionsCallbackInterface.OnLine3;
                @Line4.started -= m_Wrapper.m_PlayingActionsCallbackInterface.OnLine4;
                @Line4.performed -= m_Wrapper.m_PlayingActionsCallbackInterface.OnLine4;
                @Line4.canceled -= m_Wrapper.m_PlayingActionsCallbackInterface.OnLine4;
                @Line5.started -= m_Wrapper.m_PlayingActionsCallbackInterface.OnLine5;
                @Line5.performed -= m_Wrapper.m_PlayingActionsCallbackInterface.OnLine5;
                @Line5.canceled -= m_Wrapper.m_PlayingActionsCallbackInterface.OnLine5;
                @Line6.started -= m_Wrapper.m_PlayingActionsCallbackInterface.OnLine6;
                @Line6.performed -= m_Wrapper.m_PlayingActionsCallbackInterface.OnLine6;
                @Line6.canceled -= m_Wrapper.m_PlayingActionsCallbackInterface.OnLine6;
                @Line8.started -= m_Wrapper.m_PlayingActionsCallbackInterface.OnLine8;
                @Line8.performed -= m_Wrapper.m_PlayingActionsCallbackInterface.OnLine8;
                @Line8.canceled -= m_Wrapper.m_PlayingActionsCallbackInterface.OnLine8;
                @Line9.started -= m_Wrapper.m_PlayingActionsCallbackInterface.OnLine9;
                @Line9.performed -= m_Wrapper.m_PlayingActionsCallbackInterface.OnLine9;
                @Line9.canceled -= m_Wrapper.m_PlayingActionsCallbackInterface.OnLine9;
            }
            m_Wrapper.m_PlayingActionsCallbackInterface = instance;
            if (instance != null)
            {
                @Line1.started += instance.OnLine1;
                @Line1.performed += instance.OnLine1;
                @Line1.canceled += instance.OnLine1;
                @Line2.started += instance.OnLine2;
                @Line2.performed += instance.OnLine2;
                @Line2.canceled += instance.OnLine2;
                @Line3.started += instance.OnLine3;
                @Line3.performed += instance.OnLine3;
                @Line3.canceled += instance.OnLine3;
                @Line4.started += instance.OnLine4;
                @Line4.performed += instance.OnLine4;
                @Line4.canceled += instance.OnLine4;
                @Line5.started += instance.OnLine5;
                @Line5.performed += instance.OnLine5;
                @Line5.canceled += instance.OnLine5;
                @Line6.started += instance.OnLine6;
                @Line6.performed += instance.OnLine6;
                @Line6.canceled += instance.OnLine6;
                @Line8.started += instance.OnLine8;
                @Line8.performed += instance.OnLine8;
                @Line8.canceled += instance.OnLine8;
                @Line9.started += instance.OnLine9;
                @Line9.performed += instance.OnLine9;
                @Line9.canceled += instance.OnLine9;
            }
        }
    }
    public PlayingActions @Playing => new PlayingActions(this);
    public interface IPlayingActions
    {
        void OnLine1(InputAction.CallbackContext context);
        void OnLine2(InputAction.CallbackContext context);
        void OnLine3(InputAction.CallbackContext context);
        void OnLine4(InputAction.CallbackContext context);
        void OnLine5(InputAction.CallbackContext context);
        void OnLine6(InputAction.CallbackContext context);
        void OnLine8(InputAction.CallbackContext context);
        void OnLine9(InputAction.CallbackContext context);
    }
}
